# Generated by Django 5.0.14 on 2025-10-06 09:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_sold', models.IntegerField(help_text='Quantity of items sold', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_cost', models.DecimalField(decimal_places=2, help_text='Total selling price (auto-calculated)', max_digits=10)),
                ('profit', models.DecimalField(decimal_places=2, help_text='Total profit from this sale (auto-calculated)', max_digits=10)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(blank=True, help_text='Optional customer name', max_length=200, null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional sale notes', null=True)),
                ('product', models.ForeignKey(help_text='Product being sold', on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('sold_by', models.ForeignKey(blank=True, help_text='User who made this sale', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-date_sold'],
            },
        ),
    ]
